name: Run tests and build JAR

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Step 1 - Checkout repository
              uses: actions/checkout@v4
            # -----------------
            - name: Step 2 - Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "17"
            # -----------------
            - name: Step 3 - Build project and run tests
              run: mvn -B clean verify --file pom.xml
            # -----------------
            - name: Step 4 - Reading directory
              run: |
                  echo "Listing 'target' directory tree:"
                  tree target
